import assert from 'node:assert/strict';
import { withBrowser } from './browser-harness.mjs';
const url = process.env.GRIDBOUND_URL || 'http://127.0.0.1:5180/';
await withBrowser(async ({ send, wait, evaluate, screenshot, click, key, errors }) => {
  await send('Page.navigate', { url });
  await wait('window.gridbound && document.querySelector("canvas")');
  assert.equal(await evaluate('Boolean(document.querySelector("#town-screen:not([hidden])"))'), true, 'Fresh game must open the town, not a nine-hero raid');
  assert.deepEqual(await evaluate('window.gridbound.profile().roster'), [0, 4, 3]);
  await screenshot('artifacts/town-desktop.png');
  await click('[data-facility="party"]');
  await screenshot('artifacts/training-desktop.png');
  await click('[data-talent="active-2"]');
  assert.ok((await evaluate('window.gridbound.profile().loadouts[0].talents')).includes('active-2'));
  await evaluate(`(() => {const s=document.querySelector('[data-equip-slot="1"]');s.value='2';s.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  assert.deepEqual(await evaluate('window.gridbound.profile().loadouts[0].skills'), [0,2]);
  await click('[data-facility="campaign"]');
  await click('[data-depart="adventure"]');
  await wait('window.gridbound.battle.status === "ready" && document.querySelector("#start")');
  await screenshot('artifacts/battle-ready-desktop.png');
  await click('#start');
  await wait('window.gridbound.battle.status === "fighting"');
  const before = await evaluate('window.gridbound.battle.taps');
  await click('[data-tap="3"]');
  assert.equal(await evaluate('window.gridbound.battle.taps'), before + 1);
  await screenshot('artifacts/battle-desktop.png');
  await click('#pause');
  await wait('window.gridbound.battle.status === "paused"');
  const time = await evaluate('window.gridbound.battle.time');
  await evaluate('window.gridbound.step(5)');
  assert.equal(await evaluate('window.gridbound.battle.time'), time);
  await key('Escape');
  await wait('window.gridbound.battle.status === "fighting"');
  const gold = await evaluate('window.gridbound.profile().gold');
  for (let stage = 0; stage < 4; stage++) {
    await evaluate('window.gridbound.battle.bossHp=0; window.gridbound.step(.1)');
    await wait('document.querySelector("#modal").open');
    if (stage < 3) {
      assert.equal(await evaluate('window.gridbound.profile().gold'),gold,'Intermission must not bank expedition gold');
      await click('#next-wave');
      await click('#start');
      assert.equal(await evaluate('window.gridbound.battle.stage'),stage+1);
    }
  }
  await screenshot('artifacts/campaign-victory.png');
  assert.ok((await evaluate('window.gridbound.profile().roster')).includes(2),'First clear recruits Sable');
  const banked = await evaluate('window.gridbound.profile().gold');
  assert.ok(banked > gold);
  await key('Escape');
  await click('#start');
  assert.equal(await evaluate('window.gridbound.profile().gold'), banked,'Reopen cannot duplicate reward');
  await click('#result-town');
  await wait('document.querySelector("#town-screen:not([hidden])")');
  await click('[data-zone="1"]');
  assert.match(await evaluate('document.querySelector(".mission-brief h3").textContent'),/Sunken/);
  await send('Page.reload');
  await wait('window.gridbound && document.querySelector("[data-zone] ")');
  assert.equal(await evaluate('window.gridbound.profile().gold'),banked);
  assert.deepEqual(await evaluate('window.gridbound.profile().loadouts[0].skills'),[0,2]);
  await click('[data-view="endless"]');
  await click('[data-depart="endless"]');
  await click('#start');
  await evaluate('window.gridbound.battle.bossHp=0; window.gridbound.step(.1)');
  await wait('document.querySelector("[data-boon]")');
  assert.equal(await evaluate('document.querySelectorAll("[data-boon]").length'),3);
  await screenshot('artifacts/boon-choice.png');
  const boon=await evaluate('document.querySelector("[data-boon]").dataset.boon');
  await click('[data-boon]');
  assert.equal(await evaluate('window.gridbound.battle.floor'),2);
  assert.ok((await evaluate('window.gridbound.battle.boons')).includes(boon));
  await screenshot('artifacts/endless-floor2.png');
  await click('#start');
  await evaluate('window.gridbound.battle.heroes.forEach(h=>h.hp=0);window.gridbound.step(.1)');
  await wait('document.querySelector("#retry")');
  await click('#retry');
  assert.equal(await evaluate('window.gridbound.battle.floor'),1);
  assert.deepEqual(await evaluate('window.gridbound.battle.boons'),[]);
  assert.deepEqual(errors, []);
  const network = await evaluate(`performance.getEntriesByType('resource').filter(r=>!r.name.startsWith(location.origin)&&!r.name.startsWith('data:')&&!r.name.startsWith('blob:')).map(r=>r.name)`);
  assert.deepEqual(network,[]);
  console.log('PASS desktop: town, 3 starters, training, slot persistence, real tap, pause, four campaign stages, recruitment, idempotent rewards, zone unlock, three boons, next floor, defeat/retry, local-only network, zero runtime exceptions');
});
