import { writeFileSync,mkdirSync } from 'node:fs';
import { KITS } from '../src/game/content';
import { CHARACTERS } from '../src/game/characters';
import { JOBS,GEAR,GEAR_SETS } from '../src/game/jobs';
import { CAMPAIGN,ENEMIES,BOONS } from '../src/game/world';
import { TALENTS } from '../src/game/talents';
import { QUESTS } from '../src/game/quests';
import { MAX_HERO_LEVEL,LEVEL_THRESHOLDS } from '../src/game/levels';
import { DEPTHS,DUNGEON_EVENTS,DUNGEON_ROWS,CAMP_ROW,MATERIALS,DUNGEON_HP,DUNGEON_DMG,DEPTH_DMG } from '../src/game/dungeon';
import { STAR_PAR_SECONDS,STARS_PER_CHEST,MAX_STARS,heroicReward,chestReward } from '../src/game/journey';
import { RECOMMENDED_POWER } from '../src/game/power';
import { REFINE_STEP,MAX_REFINE } from '../src/game/jobs';
import { HEROIC_HP,HEROIC_DMG,HEROIC_INTERVAL } from '../src/game/simulation';
const database={schemaVersion:4,title:'Gridbound: Ashes of the Bell',characters:CHARACTERS,basicJobs:KITS,advancedJobs:JOBS,talents:TALENTS,equipment:GEAR,equipmentSets:GEAR_SETS,quests:QUESTS,progression:{maxLevel:MAX_HERO_LEVEL,xpThresholds:LEVEL_THRESHOLDS,skillPointsPerLevel:1},monsters:ENEMIES,boons:BOONS,recommendedPower:RECOMMENDED_POWER,stars:{parSeconds:STAR_PAR_SECONDS,perChest:STARS_PER_CHEST,max:MAX_STARS,chests:Array.from({length:Math.floor(MAX_STARS/STARS_PER_CHEST)},(_,i)=>chestReward(i+1))},heroic:{hp:HEROIC_HP,damage:HEROIC_DMG,interval:HEROIC_INTERVAL,potions:1,rewards:CAMPAIGN.map((_,i)=>heroicReward(i))},refine:{step:REFINE_STEP,max:MAX_REFINE,materials:MATERIALS},undercroft:{rows:DUNGEON_ROWS,campRow:CAMP_ROW,hp:DUNGEON_HP,damage:DUNGEON_DMG,depths:DEPTHS.map((d,i)=>({...d,damageTrim:DEPTH_DMG[i]})),events:DUNGEON_EVENTS},campaign:CAMPAIGN.map((chapter,i)=>({...chapter,number:i+1,act:Math.floor(i/4)+1,stages:chapter.stages.map(s=>({...s,combatHp:Math.round(s.hp*(i<4?2.2:4+(i+1)*.75))}))}))};
mkdirSync('data',{recursive:true});writeFileSync('data/database.json',JSON.stringify(database,null,2)+'\n');
console.log(JSON.stringify({characters:CHARACTERS.length,basicJobs:Object.keys(KITS).length,advanced:Object.values(JOBS).filter(j=>j.tier===2).length,third:Object.values(JOBS).filter(j=>j.tier===3).length,skills:Object.values(KITS).reduce((sum,k)=>sum+k.skills.length,0),talents:TALENTS.length,gear:GEAR.length,sets:GEAR_SETS.length,quests:QUESTS.length,maxHeroLevel:MAX_HERO_LEVEL,monsters:Object.keys(ENEMIES).length,boons:BOONS.length,chapters:CAMPAIGN.length,depths:DEPTHS.length,dungeonEvents:Object.keys(DUNGEON_EVENTS).length,encounters:CAMPAIGN.reduce((sum,c)=>sum+c.stages.length,0)}));
