import { mkdirSync,existsSync,copyFileSync,writeFileSync,readFileSync } from 'node:fs';
const d=JSON.parse(readFileSync('data/database.json','utf8'));
mkdirSync('docs',{recursive:true});
if(!existsSync('docs/GDD-PROTOTYPE-ARCHIVE.md'))copyFileSync('Gridbound_GDD_GRID_RAID.md','docs/GDD-PROTOTYPE-ARCHIVE.md');
const table=(headers:string[],rows:unknown[][])=>`| ${headers.join(' | ')} |\n| ${headers.map(()=>'---').join(' | ')} |\n${rows.map(row=>'| '+row.map(x=>String(x).replaceAll('|','/').replaceAll('\n',' ')).join(' | ')+' |').join('\n')}\n`;
let text=`# Gridbound: Ashes of the Bell — GDD v0.4\n\nThis document describes the implemented browser game. The earlier, broader proposal is archived in [docs/GDD-PROTOTYPE-ARCHIVE.md](docs/GDD-PROTOTYPE-ARCHIVE.md). Runtime TypeScript is authoritative; this document and data/database.json are generated from those definitions. Story spoilers follow.\n\n## 1. Product and pillars\n\nA mobile-friendly real-time grid RPG with an authored four-act campaign and repeatable raids/roguelike. Preparation creates a build; taps create tempo; telegraphs create tactical decisions. The story concerns memory, consent and the cost of a sanctuary that refuses to let tomorrow happen. The town is a preparation hub with war table, training, forge, bestiary and journal—not a free-roaming walking simulation.\n\n## 2. Full playable loop\n\nTown → assign two skills, talents, job and three equipment slots → place heroes → depart → read encounter beat → Begin → waves → miniboss → boss → return with banked loot and first-clear progression. Chapters 1–4 have four stages each; chapters 5–16 have five. There are 76 encounters, not 76 unique enemy models. HP, cooldown, formation and potion attrition carry between stages; surviving heroes receive a small 8% HP breather. Downed allies remain down until town. Quitting or losing an unfinished expedition forfeits carried loot. Replaying a completed chapter grants encounter gold but not another campaign-rank bonus or recruit; hero XP is repeatable.\n\n## 3. Input and pacing\n\nTap the sprite-area button marked TAP ↓ CD. A separate small chip beneath it changes stance. At tested mobile widths the chip is 24 px high and the tap area at least 44 px high; they do not overlap. Larger skill and movement alternatives exist in the selected-character panel. Two simultaneous touches can accelerate separate heroes. Drag/swap uses atomic grid relocation with 0.9 seconds cooldown penalty, except preparation is free. Relocation talents/boons reduce that penalty. Stance switching preserves normalized cooldown progress.\n\nA fresh tap removes 0.62 seconds before talents; an accepted sync tap removes 0.85. Repeats within 0.11 seconds are rejected. Fatigue reduces the bonus, encouraging rotation. The simulation ticks at 60 Hz independently of rendering. It uses seeded RNG and has terminal-state guards.\n\n## 4. Characters and recruitment\n\nStart with Aldric, Lyra and Rowan. Additional recruits arrive on first clears of the opening four chapters, ultimately forming a nine-hero party. Recruitment assigns an unoccupied formation tile.\n\n`;
text+=table(['Hero','Basic job','Biography'],d.characters.map((c:any)=>[c.name,c.classId,c.bio]));
text+='\n## 5. Jobs and specialization\n\nEach basic job branches into two mutually exclusive advanced jobs at campaign rank 4; each advanced job leads to one third job at campaign rank 10. A third job requires the correct advanced parent. Advanced promotion costs 180g; third promotion costs 420g. Promoting opens an active skill and a passive specialty. The player must explicitly equip the unlocked skill into one of the two slots. Third jobs retain access to their parent skill. A full respec refunds talents and both promotion steps exactly once; equipped gear remains owned.\n\n';
text+=table(['Basic','Advanced → third','Specialty','Signature'],Object.values(d.advancedJobs).filter((j:any)=>j.tier===2).map((j:any)=>{const third:any=Object.values(d.advancedJobs).find((t:any)=>t.parent===j.id);return[j.base,`${j.name} → ${third.name}`,`${j.description} / ${third.description}`,`${j.skill.name} → ${third.skill.name}`]}));
text+='\n## 6. Active skill database\n\nForty definitions: four foundational and four job-specific skills per basic job. Only two are equipped per hero.\n\n';
for(const [id,kit]of Object.entries(d.basicJobs)as [string,any][]){text+=`### ${kit.name}\n\n`;text+=table(['Index','Skill','Kind','Cooldown','Power','Effect'],kit.skills.map((s:any,i:number)=>[i,s.name,s.kind,s.cooldown,s.power,s.description]));}
text+='\n## 7. Talent tree\n\nFifty catalog nodes; thirty-four apply to each hero: fifteen retained foundational nodes, fifteen shared Assault/Bastion/Tempo nodes and four class-specific disciplines. New nodes require individual hero levels and earned skill points; some require both preceding branches. Only one of the three keystones can be held. Foundational talents remain gold-only for legacy compatibility. Respec returns both gold and spent points without resetting XP. Job advancement remains a separate campaign-rank system.\n\n';
text+=table(['Node','Branch/class','Hero level','Gold / SP','Prerequisite','Effect'],d.talents.map((t:any)=>[t.name,t.branch??'Foundations',t.level??1,`${t.cost}g / ${t.points??0} SP`,[t.requires,...(t.requiresAll??[])].filter(Boolean).join(' + ')||'Root',t.description]));
text+='\n## 8. Equipment and economy\n\nThree slots: weapon, armor and charm. Forty-two items include nine original items, eighteen pieces across six sets, and fifteen class weapons across three tiers. Set effects activate at two and three correctly equipped pieces; bonuses stack. Class/level gates apply before purchase. Three Unbound set pieces are quest-only, not zero-price shop items. Buying records ownership per hero; switching an owned item is free and repeated equip cannot deduct currency twice. There are no loot boxes, random affixes or monetization. Currency is earned in encounters and banked at expedition completion. Skill/gear/job effects alter the simulation, not just labels.\n\n';
text+=table(['Item','Slot','Cost','Effect'],d.equipment.map((g:any)=>[g.name,g.slot,g.cost,g.description]));
text+='\n## 9. Enemy AI and counterplay\n\nIntent selection is an authored per-archetype pattern with phase-dependent pace and seeded lane/tile choices, not a machine-learned agent. Marked weakest-target attacks choose the lowest living HP ratio. Strongest-target attacks rank living skill throughput. Their marker follows the hero until resolution; dragging does not evade a tracking attack. Front-row, lane breath and meteor attacks stay at their ground locations. Ritual attacks target all nine tiles. Guard mitigates party damage by 65% for 2.3 seconds with a 12-second cooldown. Interrupt skills can cancel an all-grid ritual; ultimate also interrupts. Shield/heal timing gives additional counterplay. Encounters enrage after 150 seconds.\n\nThe twelve base silhouettes have ash/frost/auric palette variants. Variants also adjust intent order or cadence. Strength in campaign additionally comes from encounter HP and chapter scaling.\n\n';
text+=table(['Monster','Title','Pattern','Counter'],Object.values(d.monsters).map((e:any)=>[e.name,e.title,e.patterns.join(' → '),e.counter]));
text+='\n## 10. Campaign: four acts\n\nNarrative is authored prose in Indonesian with English chapter/skill names. Chapter intros establish the mission, intermediate stages carry short story beats, and clear results deliver the next reveal. Cleared chapter intros/outros remain readable in the town journal. The ending is authored and singular, not a branching-choice system. Full text is preserved in data/database.json and src/game/story.ts.\n\n';
for(const c of d.campaign){text+=`### ${c.number}. ${c.name}\n\n${c.subtitle}\n\n**${c.speaker}**\n\n${c.intro}\n\n`;text+=table(['Stage','Role','Enemy','Combat HP','Beat'],c.stages.map((s:any)=>[s.name,s.kind,s.enemy,s.combatHp,s.beat??'Opening-act encounter']));text+=`\n**Aftermath:** ${c.outro}\n\nReward: ${c.reward}g zone bonus. Recruits: ${c.recruit.map((id:number)=>d.characters[id].name).join(', ')||'none'}.\n\n`;}
text+='\n## 11. Raids and roguelike\n\nRaids select any of twelve base silhouettes and all forty-eight variants. The new lantern-eater moth, basilisk, river crab and revenant are hunt/raid opponents and enter the endless rotation; the sixteen authored campaign chapters retain their existing opponents. Contract level follows cleared campaign chapters, while HP also scales to roster size. Sunken Bell starts a fresh floor-one run with the prepared roster and no boons; persistent job/gear/talents carry in. Each victory banks reward and offers up to three distinct, not-yet-owned boons. Select one, fully recover and descend. All twelve can be collected; a dedicated continuation button prevents an exhausted draft from trapping the run. Death or return to town clears run boons.\n\n';
text+=table(['Boon','Patron','Effect'],d.boons.map((b:any)=>[b.name,b.patron,b.description]));
text+='\n## 12. Architecture, saves and delivery\n\nPhaser 3 + TypeScript + Vite, procedural pixel art, Web Audio, local fonts. No runtime server or third-party network dependency. Profile validation repairs invalid skills, impossible jobs, equipment ownership, chapter gaps and duplicate tile placement. Profile v3 uses gridbound.v3. A valid v2 save migrates automatically and remains untouched for rollback; existing heroes receive XP corresponding to campaign rank. Corrupt or future-version primary saves disable writes rather than overwriting the original. Recruits join at the existing roster median level. A JSON backup download is available in Settings. Live combat is not persisted. Saves are tied to origin/browser. Development-only QA exposes snapshots and fixed-step simulation; production bundles do not expose that API.\n\nProduction uses relative asset URLs and independently cached engine/application chunks. Upload dist contents to a static host, including a nested subfolder. Netlify and Vercel configurations are included. CI regenerates the database, checks it against Git, tests, builds and runs the full campaign policy.\n\n## 13. Verification and honest boundaries\n\nSee PLAYTEST.md for executed commands. Automated policy tests establish reachability, not subjective fun. Browser campaign tests force terminal HP solely to exercise transitions; full simulation benchmarks separately fight every encounter normally. Physical touch feel, Safari/Firefox, low-end performance and human difficulty testing remain unverified. No multiplayer, cloud save, voiceover, free-roaming town, procedural narrative or paid economy is implemented. The broad prototype archive contains ideas that are not acceptance criteria for this release.\n';
text+='\n## 14. Individual hero progression and quests\n\nHero XP and campaign rank are separate. Each hero starts at level 1 and caps at level 40, gaining one skill point per level. Levels increase HP and power; only expedition participants earn combat XP, with downed heroes receiving 60%. XP and hunt counters settle once at a completed expedition/floor; defeat or an unfinished chapter earns neither. Successful replays continue earning XP. Quest XP goes to the selected recruited hero, except companion rewards always go to their named hero.\n\nThirty quests: twelve hunts, six chained town requests, nine companion milestones and three chained endless milestones. Objectives recognize recorded lifetime achievements; hunt counters begin with v3 migration rather than inventing past kills. Rewards are claimed manually once, never auto-spent. Tracking does not reset objective counters. Locked prerequisites and already claimed rewards cannot be bypassed through the UI.\n\n';
text+=table(['Quest','Kind / giver','Unlock / objective','Gold / XP','Item reward'],d.quests.map((q:any)=>[q.name,`${q.kind} / ${q.giver}`,`${q.chapter} clears; ${q.requires??'no prior quest'}; ${q.metric} ${q.target}${q.enemy?' '+q.enemy:''}`,`${q.gold}g / ${q.xp} XP`,q.gear??'None']));
text+='\n### Equipment sets\n\n';text+=table(['Set','Two pieces','Three pieces'],d.equipmentSets.map((s:any)=>[s.name,JSON.stringify(s.two),JSON.stringify(s.three)]));
text+='\n### XP thresholds (cumulative)\n\n';text+=table(['Hero level','Total XP'],d.progression.xpThresholds.map((xp:number,i:number)=>[i+1,xp]));
text+='\n## 15. GUI interaction and next production\n\nTraining is split into overview, active skills, jobs, talent branches, equipment and formation. Campaign, quests and bestiary use single-record listing pages. Talent branches draw SVG prerequisite arrows; selecting a node shows its detail and a separate learn action. Equipment selection previews description, cost, restrictions and stat comparison without spending; explicit confirmation applies the purchase/equip. Victory waits for enemy death readiness (780ms normal, 120ms reduced-motion fade), then result choices remain disabled for one full second. Save loading protects incomplete v3 envelopes instead of overwriting legacy progress.\n\nImplemented does not mean visually accepted or deployed. Default-page height measurements still show some vertical scroll; expanded content, final combat bounds, physical devices and arrow clarity require review. See [docs/NEXT-PRODUCTION.md](docs/NEXT-PRODUCTION.md) for current status, ordered blockers, release acceptance and rollback. See [docs/GUI-VERIFIED.md](docs/GUI-VERIFIED.md) for the latest executed GUI checkpoint. Do not use old agent snapshots as current release evidence.\n';
writeFileSync('Gridbound_GDD_GRID_RAID.md',text);console.log(`GDD generated: ${text.length} characters`);
