import assert from 'node:assert/strict';
import { withBrowser } from './browser-harness.mjs';
const url=process.env.GRIDBOUND_URL||'http://127.0.0.1:5180/';
for(const width of [360,390])await withBrowser(async({send,evaluate,wait,click,key,screenshot,errors})=>{
 await send('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.removeItem('gridbound.v3');localStorage.removeItem('gridbound.v2');`});
 await send('Page.navigate',{url});await wait('window.gridbound && window.gridbound.scene?.textures?.exists("dragon-auric-0")');
 const fits=async()=>assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'),`No horizontal overflow ${width}`);
 await fits();await screenshot(`artifacts/town-${width}.png`);
 await click('[data-facility="party"]');await click('[data-training-tab="jobs"]');await fits();
 assert.equal(await evaluate('document.querySelectorAll(".job-node").length'),4);
 await click('[data-training-tab="talents"]');
 assert.equal(await evaluate('document.querySelectorAll(".talent-node").length'),1);
 await screenshot(`artifacts/training-${width}.png`);
 await click('[data-facility="campaign"]');await click('[data-depart="adventure"]');await click('#start');
 await wait('window.gridbound.battle.status==="fighting"');await fits();
 const sizes=await evaluate(`(()=>{const a=document.querySelector('[data-tap="0"]').getBoundingClientRect(),s=document.querySelector('[data-stance="0"]').getBoundingClientRect();return {tap:{w:a.width,h:a.height},skill:{w:s.width,h:s.height},overlap:a.bottom-s.top}})()`);
 assert.ok(sizes.skill.h<=28&&sizes.skill.h>=24,JSON.stringify(sizes));assert.ok(sizes.tap.h>sizes.skill.h,JSON.stringify(sizes));
 const position=async selector=>evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
 await position('#arena');
 const a=await position('[data-tap="0"]'),b=await position('[data-tap="3"]');
 const before=await evaluate('window.gridbound.battle.taps');
 await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1,radiusX:3,radiusY:3},{...b,id:2,radiusX:3,radiusY:3}]});
 await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert.equal(await evaluate('window.gridbound.battle.taps'),before+2,'two real touches accelerate separate heroes');
 const from=await position('[data-tap="0"]');
 const destination=await evaluate(`(()=>{const r=document.querySelector('#arena').getBoundingClientRect();return {x:r.left+456/600*r.width,y:r.top+630/760*r.height}})()`);
 await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...from,id:3,radiusX:3,radiusY:3}]});
 await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...destination,id:3,radiusX:3,radiusY:3}]});
 await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert.equal(await evaluate('window.gridbound.battle.hero(0).slot'),8,'real touch drag to back-right');
 await click('#pause');await key('Escape');await wait('window.gridbound.battle.status==="fighting"');
 await screenshot(`artifacts/battle-${width}.png`);
 console.log('PASS mobile',width,JSON.stringify(sizes),'two touches, drag, pause, responsive, 34 talents, 4 job nodes');
 assert.deepEqual(errors,[]);
},{width,height:844,mobile:true});
